spring.application.name=SlackX

spring.datasource.url=jdbc:postgresql://ep-solitary-butterfly-an5cvgnv-pooler.c-6.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_iszJ3uWV8fTb

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=trace
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.highlight_sql=true
spring.security.jwt.expiration=3600000
